import { AlertTriangle, ArrowRight, Clock3, MapPin, Route, Sparkles, Truck } from 'lucide-react';
import Button from '../../components/Button';
import AppShell from '../../components/AppShell';

export default function RoutePlanning() {
  return <AppShell><div className="planning-desktop"><div className="page-heading"><div><span className="eyebrow purple">Route planning</span><h1>Plan your route</h1><p>Compare safer corridors before your next dispatch.</p></div><span className="planning-status"><i /> Route intelligence online</span></div><div className="planning-workspace"><section className="planning-controls"><div className="planning-card-heading"><Route size={18} /><div><h2>New route</h2><p>Enter your journey details</p></div></div><label className="route-field"><span>From (origin)</span><div><MapPin size={15} /> Guwahati Central Depot</div></label><label className="route-field"><span>To (destination)</span><div><MapPin size={15} /> Tawang Mountain Pass Corridor</div></label><label className="route-field"><span>Vehicle profile</span><div><Truck size={15} /> Heavy goods vehicle <span className="field-chevron">⌄</span></div></label><Button>Check route <ArrowRight size={15} /></Button><div className="planning-note"><Sparkles size={15} /><span><strong>AI route optimization</strong><small>We compare weather, terrain, and road safety data.</small></span></div></section><section className="planning-results"><div className="results-top"><div><span className="eyebrow purple">Route comparison</span><h2>Recommended corridors</h2></div><span className="optimized-pill"><Sparkles size={12} /> AI Optimized</span></div><div className="desktop-route-map"><svg viewBox="0 0 760 280" role="img" aria-label="Route comparison map"><path className="map-road route-current" d="M44 216 C168 195 160 62 330 104 S510 232 712 52" /><path className="map-road route-suggested" d="M44 216 C196 258 300 208 410 190 S566 120 712 52" /><circle cx="44" cy="216" r="9" /><circle cx="712" cy="52" r="9" /><circle className="map-alert" cx="330" cy="104" r="8" /><text x="28" y="250">Guwahati</text><text x="665" y="35">Tawang</text></svg><div className="desktop-map-legend"><span><i className="legend-current" /> Route A · Current</span><span><i className="legend-safe" /> Route B · Suggested</span><span><i className="legend-alert" /> Risk area</span></div></div><div className="planning-risk"><AlertTriangle size={18} /><div><strong>High risk on current route</strong><small>6 accidents in the last month · heavy rain forecast today near Bomdila</small></div></div><div className="desktop-route-options"><RouteOption title="Route A" tag="High risk" distance="310 km" time="9h 45m" current /><RouteOption title="Route B" tag="Low risk" distance="285 km" time="8h 15m" /></div><div className="planning-actions"><Button>Accept Route B <ArrowRight size={15} /></Button><button className="continue-button">Continue current route</button></div></section></div></div></AppShell>;
}

function RouteOption({ title, tag, distance, time, current }) { return <article className={`desktop-route-option ${current ? 'current' : 'recommended'}`}><div><span className="route-option-dot" /><strong>{title}</strong><em>{tag}</em></div><small><Clock3 size={13} /> {distance} · {time}</small>{!current && <span className="best-choice">Best choice</span>}</article>; }
