import { ArrowLeft, LocateFixed, Navigation, Phone, Volume2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import AppShell from '../../components/AppShell';
import { routeApi } from '../../services/api';
import RouteMap from '../../components/RouteMap';

export default function LiveNavigation() {
  const [route, setRoute] = useState(null); const [position, setPosition] = useState(null); const [tracking, setTracking] = useState(false); const [error, setError] = useState('');
  useEffect(() => { routeApi.list().then((routes) => { if (routes[0]) setRoute(routes[0]); }).catch((requestError) => setError(requestError.message)); }, []);
  useEffect(() => { if (!route || !navigator.geolocation) { if (!navigator.geolocation) setError('Browser GPS is not available.'); return undefined; } let watchId; watchId = navigator.geolocation.watchPosition(async (location) => { const point = { latitude: location.coords.latitude, longitude: location.coords.longitude, speed_kmh: Math.max(0, (location.coords.speed || 0) * 3.6) }; setPosition(point); setTracking(true); try { await routeApi.track(route.id, point); } catch (requestError) { setError(requestError.message); } }, (geolocationError) => setError(geolocationError.message), { enableHighAccuracy: true, maximumAge: 10000, timeout: 15000 }); return () => navigator.geolocation.clearWatch(watchId); }, [route]);
  const title = route ? `${route.origin} → ${route.destination}` : 'No saved route';
  return <AppShell><div className="navigation-layout"><section className="navigation-map"><div className="map-floating"><Link to="/route-details"><ArrowLeft size={16} /> Route details</Link><span className="live-pill"><i /> {tracking ? 'Live' : 'Waiting for GPS'}</span></div><RouteMap geometry={route?.geometry} currentPosition={position} height="clamp(420px, 62vh, 680px)" /><button className="locate-button" onClick={() => navigator.geolocation?.getCurrentPosition(() => {}, () => setError('Location permission is required.'))}><LocateFixed size={18} /></button></section><aside className="navigation-panel"><span className="eyebrow purple">Live navigation</span><h1>{title}</h1>{error && <p className="error">{error}</p>}<div className="next-turn"><Navigation size={26} /><div><small>{route ? 'GPS position updates are active' : 'Create a route first'}</small><strong>{position ? `${position.latitude.toFixed(5)}, ${position.longitude.toFixed(5)}` : 'Waiting for location'}</strong></div></div><div className="nav-stats"><div><strong>{route ? `${Math.floor(route.duration_minutes / 60)}h ${route.duration_minutes % 60}m` : '--'}</strong><small>Estimated time</small></div><div><strong>{route ? `${route.distance_km} km` : '--'}</strong><small>Route distance</small></div></div><div className="nav-alert"><strong>{route?.risk_level === 'high' ? 'High risk route' : 'Route monitoring'}</strong><p>{route ? 'Location updates are saved to your route history.' : 'Plan a route to start tracking.'}</p></div><div className="navigation-actions"><button><Volume2 size={17} /> Voice guidance</button><button><Phone size={17} /> Assistance</button></div></aside></div></AppShell>;
}
