import { Bell, Map, ArrowUpRight, AlertTriangle, Truck, LogOut, Settings, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import Logo from '../../components/Logo';
import Reveal from '../../components/Reveal';
import WorkspaceMenu from '../../components/WorkspaceMenu';
import { recentRoutes, routeStats } from '../../data/mockData';

export default function Dashboard() {
  const [dark, setDark] = useState(() => localStorage.getItem('routesetu-theme') !== 'light');
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [optionsOpen, setOptionsOpen] = useState(false);
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('routesetu-theme', dark ? 'dark' : 'light'); }, [dark]);
  return <div className="dashboard"><header><div className="overview-brand"><Logo dark /><WorkspaceMenu open={optionsOpen} onToggle={() => { setOptionsOpen(!optionsOpen); setNotificationsOpen(false); setProfileOpen(false); }} /></div><nav><Link className="active" to="/dashboard">Overview</Link><Link to="/live-routes">Live Routes</Link><Link to="/alerts">Alerts</Link><Link to="/reports">Reports</Link></nav><div className="user-area"><button className="theme-toggle" onClick={() => setDark(!dark)} aria-label={`Switch to ${dark ? 'light' : 'dark'} mode`}>{dark ? '☀' : '☾'}</button><div className="header-popover-wrap"><button className="icon-button notification-trigger" onClick={() => { setNotificationsOpen(!notificationsOpen); setProfileOpen(false); }} aria-label="Open notifications"><Bell size={18} /><i /></button>{notificationsOpen && <NotificationPopover />}</div><div className="header-popover-wrap"><button className="profile-trigger" onClick={() => { setProfileOpen(!profileOpen); setNotificationsOpen(false); }}><span>RK</span><strong>Rajesh Kumar</strong></button>{profileOpen && <ProfilePopover />}</div></div></header><section className="dashboard-body"><Reveal><div className="dashboard-title"><div><span className="eyebrow purple">● Dispatch command center</span><h1>Good morning, Rajesh</h1><p>Here’s what’s happening across your North East logistics network.</p></div><Link className="button button-primary" to="/live-navigation"><Map size={16} /> View live map</Link></div></Reveal><div className="stats-row">{routeStats.map((stat, index) => <Reveal key={stat.label} delay={index * 100}><div className="stat-card"><span>{stat.label}</span><strong>{stat.value}</strong><small><ArrowUpRight size={13} /> {stat.change} from last week</small></div></Reveal>)}</div><div className="dashboard-grid"><Reveal><section className="table-card"><div className="card-title"><h2>Recent routes</h2><Link to="/route-history">View all <ArrowUpRight size={14} /></Link></div><table><thead><tr><th>Route</th><th>Status</th><th>Risk level</th><th>ETA</th></tr></thead><tbody>{recentRoutes.map((route) => <tr key={route.route}><td><Truck size={16} />{route.route}</td><td><span className="status">{route.status}</span></td><td><span className={`risk risk-${route.risk.toLowerCase()}`}>{route.risk}</span></td><td>{route.eta}</td></tr>)}</tbody></table></section></Reveal><Reveal delay={150}><section className="alert-card"><div className="card-title"><h2>Route alerts</h2><Link to="/alerts"><AlertTriangle /></Link></div><div className="alert-item"><span className="alert-dot"></span><div><strong>Heavy rainfall advisory</strong><p>NH-13 · Bomdila corridor</p><small>Updated 12 min ago</small></div></div><div className="alert-item"><span className="alert-dot yellow"></span><div><strong>Temporary checkpoint</strong><p>NH-6 · Jowai bypass</p><small>Updated 1 hour ago</small></div></div></section></Reveal></div></section></div>;
}
function NotificationPopover() { return <div className="header-popover notification-popover"><div className="popover-heading"><strong>Notifications</strong><Link to="/alerts">View all</Link></div><div className="popover-alert"><span className="popover-dot danger" /><div><strong>Heavy rainfall advisory</strong><small>NH-13 · Bomdila corridor</small><time>12 min ago</time></div></div><div className="popover-alert"><span className="popover-dot warning" /><div><strong>Temporary checkpoint</strong><small>NH-6 · Jowai bypass</small><time>1 hour ago</time></div></div></div>; }
function ProfilePopover() { return <div className="header-popover profile-popover"><div className="popover-profile"><span>RK</span><div><strong>Rajesh Kumar</strong><small>Fleet dispatcher</small></div></div><Link to="/profile"><UserRound size={15} /> View profile</Link><Link to="/settings"><Settings size={15} /> Account settings</Link><button><LogOut size={15} /> Sign out</button></div>; }
